import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog - App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Contact</li>
          <li>Blog</li>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>Blog-App</h1>   
        <p>This is blog</p>  
        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>sdbsad</h3>
            <p>kabdjkadjkasbdjksbdjksbdjk</p>
          </div>
        </div>
        <div className="blogs">
          <div className="blogItem">
            <h3>sdbsad</h3>
            <p>kabdjkadjkasbdjksbdjksbdjk</p>
          </div>
        </div>
        <div className="blogs">
          <div className="blogItem">
            <h3>sdbsad</h3>
            <p>kabdjkadjkasbdjksbdjksbdjk</p>
          </div>
        </div>
      </main>
    </>
  );
}
